services:
  - type: web
    name: task-manager
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn taskmanager.wsgi
    envVars:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: task-manager.onrender.com
